users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

verify/urls.py
from django.urls import path

from . import views


app_name = 'verify'

# Главные страницы
urlpatterns = [
     path('', views.index, name='index')
]

# Студенты
urlpatterns += [
     path('students/',
          views.student_list,
          name='student_list'),
     path('students/<str:username>/',
          views.student_active_check,
          name='student_active_check'),
]

# Группы
urlpatterns += [
     path('group/',
          views.group_list,
          name='group_list'),
     path('group/new_group/',
          views.new_group,
          name='new_group'),
     path('group/<slug:slug>/',
          views.group_students,
          name='group_students'),
]

# Проверки
urlpatterns += [
     path('user/<str:username>/check_list/',
          views.check_list,
          name='check_list'),
     path('user/<str:username>/archive/',
          views.archive,
          name='archive'),
     path('user/<str:username>/new_check/',
          views.new_check,
          name='new_check'),
     path('user/<str:username>/<int:check_id>/check_view/',
          views.check_view,
          name='check_view'),
     path('user/<str:username>/<int:check_id>/check_delete/',
          views.check_delete,
          name='check_delete'),
     path('user/<str:username>/<int:check_id>/check_archive/',
          views.check_archive,
          name='check_archive'),
     path('user/<str:username>/<int:check_id>/check_active/',
          views.check_active,
          name='check_active'),
]


# Замечания
urlpatterns += [
     path('user/<str:username>/<int:check_id>/add_remark/',
          views.add_remark,
          name='add_remark'),
     path('user/<str:username>/<int:check_id>/<int:remark_id>/delete_remark/',
          views.delete_remark,
          name='delete_remark'),
     path('user/<str:username>/<int:check_id>/<int:remark_id>/edit_remark/',
          views.edit_remark,
          name='edit_remark'),
]

verify/forms.py
from django import forms

from users.models import Group

from . import constants as cts
from .models import CheckOut, Remark


class RemarkNavForm(forms.Form):
    """Форма для указания страницы и абзаца замечания."""
    SECTION_CHOICES = (
        ('title', 'Титульный лист'),
        ('task', 'Индивидуальное задание на ВКР'),
        ('abstract', 'Реферат'),
        ('contents', 'Содержание'),
        ('introduction', 'Введение'),
        ('body', 'Основная часть'),
        ('conclusion', 'Заключение'),
        ('source', 'Список использованных источников'),
        ('attachment', 'Приложение'),
    )
    section = forms.ChoiceField(
        label='Раздел ПЗ',
        choices=SECTION_CHOICES)
    page_number = forms.CharField(
        label='Номер страницы',
        required=False)
    paragraph = forms.CharField(
        label='Номер абзаца',
        required=False)
    check_all = forms.BooleanField(
        label='Проверить по всей работе',
        required=False)
    custom_error = forms.CharField(
        label='Замечание:',
        widget=forms.Textarea(attrs={'style': 'height: 105px'}),
        required=False
    )


class RemarkEditForm(forms.ModelForm):
    """Форма редактирования замечания."""
    class Meta:
        model = Remark
        fields = ('section', 'page_number', 'paragraph', 'text',)


class RemarkStandartErrorForm(forms.Form):
    """Форма выбора замечания."""
    # [ERROR_MAIN]
    err_main_1 = forms.BooleanField(label=cts.ERROR_MAIN_1, required=False)
    err_main_2 = forms.BooleanField(label=cts.ERROR_MAIN_2, required=False)
    err_main_3 = forms.BooleanField(label=cts.ERROR_MAIN_3, required=False)
    err_main_4 = forms.BooleanField(label=cts.ERROR_MAIN_4, required=False)
    err_main_5 = forms.BooleanField(label=cts.ERROR_MAIN_5, required=False)
    err_main_6 = forms.BooleanField(label=cts.ERROR_MAIN_6, required=False)
    err_main_7 = forms.BooleanField(label=cts.ERROR_MAIN_7, required=False)
    err_main_8 = forms.BooleanField(label=cts.ERROR_MAIN_8, required=False)
    # [ERROR_TEXT]
    err_text_1 = forms.BooleanField(label=cts.ERROR_TEXT_1, required=False)
    err_text_2 = forms.BooleanField(label=cts.ERROR_TEXT_2, required=False)
    err_text_3 = forms.BooleanField(label=cts.ERROR_TEXT_3, required=False)
    err_text_4 = forms.BooleanField(label=cts.ERROR_TEXT_4, required=False)
    # [ERROR_HEADERS]
    err_header_1 = forms.BooleanField(label=cts.ERROR_HEAD_1, required=False)
    err_header_2 = forms.BooleanField(label=cts.ERROR_HEAD_2, required=False)
    err_header_3 = forms.BooleanField(label=cts.ERROR_HEAD_3, required=False)
    # [ERROR_LIST]
    err_list_1 = forms.BooleanField(label=cts.ERROR_LIST_1, required=False)
    # [ERROR_TABLE]
    err_table_1 = forms.BooleanField(label=cts.ERROR_TABLE_1, required=False)
    err_table_2 = forms.BooleanField(label=cts.ERROR_TABLE_2, required=False)
    err_table_3 = forms.BooleanField(label=cts.ERROR_TABLE_3, required=False)
    err_table_4 = forms.BooleanField(label=cts.ERROR_TABLE_4, required=False)
    # [ERROR_IMAGE]
    err_image_1 = forms.BooleanField(label=cts.ERROR_IMAGE_1, required=False)
    err_image_2 = forms.BooleanField(label=cts.ERROR_IMAGE_2, required=False)
    err_image_3 = forms.BooleanField(label=cts.ERROR_IMAGE_3, required=False)
    err_image_4 = forms.BooleanField(label=cts.ERROR_IMAGE_4, required=False)
    # [ERROR_FORMULA]
    err_formula_1 = forms.BooleanField(label=cts.ERROR_FORMULA_1,
                                       required=False)
    err_formula_2 = forms.BooleanField(label=cts.ERROR_FORMULA_2,
                                       required=False)
    err_formula_3 = forms.BooleanField(label=cts.ERROR_FORMULA_3,
                                       required=False)
    # [ERROR_FRAME]
    err_frame_1 = forms.BooleanField(label=cts.ERROR_FRAME_1, required=False)
    err_frame_2 = forms.BooleanField(label=cts.ERROR_FRAME_2, required=False)
    # [ERROR_LINK]
    err_link_1 = forms.BooleanField(label=cts.ERROR_LINK_1, required=False)
    err_link_2 = forms.BooleanField(label=cts.ERROR_LINK_2, required=False)


class CheckForm(forms.ModelForm):
    class Meta:
        model = CheckOut
        fields = ('docx_file', 'pdf_file', 'info')

    def clean_docx_file(self):
        data = self.cleaned_data['docx_file']
        file_type = data.name.split('.')[-1]
        if file_type != 'docx':
            raise forms.ValidationError(
                'Файл должен иметь расширение .docx',
            )
        if data.size > 8000000:
            raise forms.ValidationError(
                'Файл должен иметь размер не более 8 Мб',
            )
        return data

    def clean_pdf_file(self):
        data = self.cleaned_data['pdf_file']
        file_type = data.name.split('.')[-1]
        if file_type != 'pdf':
            raise forms.ValidationError("Файл должен иметь расширение .pdf",
                                        code='invalid extension')
        if data.size > 8000000:
            raise forms.ValidationError(
                'Файл должен иметь размер не более 8 Мб',
            )
        return data


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title',)

verify/views/check_views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail

from verify.decorators import user_access, user_check
from verify.forms import CheckForm, RemarkNavForm, RemarkStandartErrorForm
from verify.models import CheckOut
from django.contrib.auth.models import User

User = get_user_model()


@login_required
@user_check
def check_list(request, username):
    """Выводит список активных заявок для запрошенного пользователя."""
    user = get_object_or_404(User, username=username)
    check_list = CheckOut.objects.all().filter(status=False)
    if not user.allow_manage:
        check_list = check_list.filter(student__username=username)
    paginator = Paginator(check_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'active': True, 'username': username}
    return render(request, 'verify/check_list.html', context)


@login_required
@user_check
def archive(request, username):
    """Выводит список архивных заявок для запрошенного пользователя."""
    user = get_object_or_404(User, username=username)
    check_list = CheckOut.objects.all().filter(status=True)
    if not user.allow_manage:
        check_list = check_list.filter(student__username=username)
    paginator = Paginator(check_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'active': False, 'username': username}
    return render(request, 'verify/check_list.html', context)


@login_required
@user_check
def check_view(request, username, check_id):
    """Выводит данные по конкретной заявке для запрошенного пользователя."""
    # Формы под вопросом
    check_item = get_object_or_404(CheckOut, id=check_id)
    form_1 = RemarkNavForm(request.POST or None)
    form_2 = RemarkStandartErrorForm(request.POST or None)
    remarks = check_item.remark.all()
    context = {
        'username': username,
        'check_item': check_item,
        'remarks': remarks,
        'form_1': form_1,
        'form_2': form_2,
    }
    return render(request, 'verify/check_view.html', context)


@login_required
@user_access
def check_archive(request, username, check_id):
    """Отправляет определенную заявку в архив."""
    check_item = get_object_or_404(CheckOut, id=check_id)
    check_item.status = True
    check_item.pdf_file.delete()
    check_item.docx_file.delete()
    check_item.save()
    return redirect('verify:check_list', username)


@login_required
@user_access
def check_active(request, username, check_id):
    """Делает определенную заявку активной."""
    check_item = get_object_or_404(CheckOut, id=check_id)
    check_item.status = False
    check_item.save()
    return redirect('verify:check_list', username)


@login_required
@user_check
def check_delete(request, username, check_id):
    """Удаляет определенную заявку из БД."""
    get_object_or_404(CheckOut, id=check_id).delete()
    return redirect('verify:check_list', username)


@login_required
@user_check
def new_check(request, username):
    """Создает новую заявку от лица текущего пользователя."""
    student_check = request.user.checkout_student
    if student_check.exists() and not student_check.last().status:
        return redirect('verify:check_list', username)
    form = CheckForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'verify/new_check.html', {'form': form})
    check = form.save(commit=False)
    check.student = request.user
    check.save()

    # sending msg to superuser mail

    superusers = User.objects.filter(is_superuser=True)

    if superusers.exists():
        subject = 'Hовый запрос на проверку работы!'
        message = f'Hовый запрос на проверку работы от {request.user.username}!'
        from_email = 'pinkdumpyou@gmail.com'  # !!! REPLACE THIS EMAIL TO UR !!! ###########!!!!!!!!!!!!!!!!!

    for superuser in superusers:
        to_email = superuser.email
        send_mail(subject, message, from_email, [to_email])

        # DEBUG OUT HOW MANY MSGS WAS SESNDED TO SUPERUSERS EMAIL
        # print("superuser email: ", to_email)

    return redirect('verify:check_list', username)

verify/views/exceptions.py
from django.shortcuts import render


def bad_request(request, exception):
    return render(request, 'misc/400.html', {'path': request.path}, status=400)


def permission_denied(request, exception):
    return render(request, 'misc/403.html', {'path': request.path}, status=403)


def page_not_found(request, exception):
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'misc/500.html', status=500)

verify/views/group_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from users.models import Group
from verify.decorators import user_access
from verify.forms import GroupForm


@login_required
@user_access
def group_list(request):
    """Выводит таблицу всех зарегистрированных групп."""
    group_list = Group.objects.all()
    context = {'group_list': group_list}
    return render(request, 'verify/group_list.html', context)


@login_required
@user_access
def group_students(request, slug):
    """Выводит таблицу студентов заданной группы."""
    group = get_object_or_404(Group, slug=slug)
    students = group.user.all()
    context = {'students': students, 'group': group}
    return render(request, 'verify/student_list.html', context)


@login_required
@user_access
def new_group(request):
    """Создает новую студенческую группу."""
    form = GroupForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'verify/new_group.html', {'form': form})
    form.save()
    return redirect('verify:check_list', request.user.username)

verify/views/remark_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from verify.decorators import user_access
from verify.forms import RemarkEditForm, RemarkNavForm, RemarkStandartErrorForm
from verify.models import CheckOut, Remark


@login_required
@user_access
def add_remark(request, username, check_id):
    """Добавляет замечание на основе формы."""
    check_item = get_object_or_404(CheckOut, id=check_id)
    form_1 = RemarkNavForm(request.POST or None)
    form_2 = RemarkStandartErrorForm(request.POST or None)
    if form_1.is_valid() and form_2.is_valid():
        choice = form_1.cleaned_data['section']
        section = dict(form_1.fields['section'].choices)[choice]
        page_number = form_1.cleaned_data.get('page_number')
        paragraph = form_1.cleaned_data.get('paragraph')
        check_all = form_1.cleaned_data.get('check_all')
        custom_error = form_1.cleaned_data.get('custom_error')
        # Создаем кастомную ошибку, если это требуется
        if custom_error != '':
            check_all_status = None
            if check_all:
                check_all_status = form_1.fields.get('check_all').label,
            Remark.objects.get_or_create(
                section=section,
                page_number=page_number,
                paragraph=paragraph,
                check_all=check_all_status,
                text=custom_error,
                author=request.user,
                check_out=check_item
            )
        # Проверяем поля формы и создаем ошибки
        for field in form_2.fields:
            checkbox_result = form_2.cleaned_data.get(field)
            if checkbox_result:
                check_all_status = None
                if check_all:
                    check_all_status = form_1.fields.get('check_all').label,
                Remark.objects.get_or_create(
                    section=section,
                    page_number=page_number,
                    paragraph=paragraph,
                    check_all=check_all_status,
                    text=form_2.fields.get(field).label,
                    author=request.user,
                    check_out=check_item
                )
    return redirect('verify:check_view', username, check_id)


@login_required
@user_access
def edit_remark(request, username, check_id, remark_id):
    """Редактирует замечание."""
    remark = get_object_or_404(Remark, id=remark_id)
    form = RemarkEditForm(request.POST or None, instance=remark)
    if not form.is_valid():
        context = {'form': form}
        return render(request, 'verify/edit_remark.html', context)
    remark.save()
    return redirect('verify:check_view', username, check_id)


@login_required
@user_access
def delete_remark(request, username, check_id, remark_id):
    """Удаляет замечание."""
    remark = get_object_or_404(Remark, id=remark_id)
    remark.delete()
    return redirect('verify:check_view', username, check_id)

verify/views/static_pages.py
from django.shortcuts import render


def index(request):
    """Главная страница информационной системы."""
    return render(request, 'verify/index.html')

verify/views/student_views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from verify.decorators import user_access
from verify.models import CheckOut

User = get_user_model()


@login_required
@user_access
def student_list(request):
    """Выводит таблицу всех зарегистрированных студентов."""
    students = User.objects.all().exclude(username='admin')
    students = students.exclude(allow_manage=True)
    context = {'students': students}
    return render(request, 'verify/student_list.html', context)


@login_required
@user_access
def student_active_check(request, username):
    """Выводит активную заявку определенного студента."""
    student_check = CheckOut.objects.all().filter(status=False)
    student_check = student_check.filter(student__username=username).first()
    context = {'student_check': student_check}
    return render(request, 'verify/student_active_check.html', context)

templates/verify/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %} Нормоконтроль {% endblock %}</title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
  {% include "includes/nav.html" %}
  <main class="min-vh-100">
    <div class="container">
      <div class="container">
        <h2>{% block header %}{% endblock %}</h2>
      </div>
      <p>{% block description %}{% endblock %}</p>
      {% block content %}{% endblock %}
    </div>
  </main>
  {% include "includes/footer.html" %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>

</html>

templates/verify/check_view.html
{% extends "verify/base.html" %}
{% block title %}Проверка работы {{ check_item.student.get_full_name }}{% endblock %}
{% block header %}Проверка №{{ check_item.student.checkout_student.count }}. Студент - {{ check_item.student.get_full_name }}. Группа - {{ check_item.student.group }}{% endblock %}
{% block description %}{% endblock %}
{% block content %}
{% load user_filters %}
{% load static %}
<div class="container">
  {% if check_item.docx_file and check_item.pdf_file %}
  <p>Отправлено {{ check_item.check_date }}, <a href="{{ check_item.pdf_file.url }}">скачать pdf</a>, <a href="{{ check_item.docx_file.url }}">скачать docx</a></p>
  {% endif %}
  <form method="post" action="{% url 'verify:add_remark' username check_item.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {% if not check_item.status %}
    <button type="button" class="btn btn-dark mb-2" data-bs-toggle="modal" data-bs-target="#exampleModal2">
      Добавить замечания
    </button>
    {% endif %}
    <button type="button" class="btn btn-danger mb-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Показать замечания ({{ check_item.remark.count}})
    </button>
    {% if not check_item.status %}
    <a type="button" class="btn btn-success mb-2" href="{% url 'verify:check_archive' username check_item.id %}" role="button">
      Завершить проверку
    </a>
    {% endif %}
    {% if check_item.pdf_file %}
    <iframe src="https://docs.google.com/viewer?url=https://normocontrol22.pythonanywhere.com{{ check_item.pdf_file.url }}&embedded=true" width="1000" height="800" style="border: 1;"></iframe>
    {% endif %}
    <!-- Modal 1-->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Замечания по работе - {{ check_item.student.get_full_name }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {% include "includes/remarks.html" %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal 2-->
    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <button type="submit" class="btn btn-success">
              Добавить замечание
            </button>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <!-- error form body-->
            <div class="row">
              <div class="col-sm">
                <div class="card mb-2">
                  <div class="card-header">
                    Расположение ошибки
                  </div>
                  <div class="card-body">
                    <div class="row">
                      <div class="col">
                        <div class="form-group row">
                          <label class="col-md-4 col-form-label">
                            {{ form_1.section.label }}
                          </label>
                          <div class="col-md-7 m-1">
                            {{ form_1.section|addclass:"form-control" }}
                          </div>
                        </div>
                        <div class="form-group row">
                          <label class="col-md-4 col-form-label">
                            {{ form_1.page_number.label }}
                          </label>
                          <div class="col-md-7 m-1">
                            {{ form_1.page_number|addclass:"form-control" }}
                          </div>
                        </div>
                        <div class="form-group row">
                          <label class="col-md-4  col-form-label">
                            {{ form_1.paragraph.label }}
                          </label>
                          <div class="col-md-7 m-1">
                            {{ form_1.paragraph|addclass:"form-control" }}
                          </div>
                        </div>
                      </div>
                      <div class="col">
                        {{ form_1.custom_error.label }}
                        <div class="form-group mt-1">
                          {{ form_1.custom_error|addclass:"form-control" }}
                        </div>
                        <div class="col-md-7 mt-1">
                          {{ form_1.check_all|addclass:"form-check-input me-1" }} {{ form_1.check_all.label }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm">
                <div class="card mb-2">
                  <div class="card-header">
                    Общие ошибки
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_main_1|addclass:"form-check-input me-1"}} {{ form_2.err_main_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_2|addclass:"form-check-input me-1"}} {{ form_2.err_main_2.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_3|addclass:"form-check-input me-1"}} {{ form_2.err_main_3.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_4|addclass:"form-check-input me-1"}} {{ form_2.err_main_4.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_5|addclass:"form-check-input me-1"}} {{ form_2.err_main_5.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_6|addclass:"form-check-input me-1"}} {{ form_2.err_main_6.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_7|addclass:"form-check-input me-1"}} {{ form_2.err_main_7.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_main_8|addclass:"form-check-input me-1"}} {{ form_2.err_main_8.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Заголовки
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_header_1|addclass:"form-check-input me-1"}} {{ form_2.err_header_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_header_2|addclass:"form-check-input me-1"}} {{ form_2.err_header_2.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_header_3|addclass:"form-check-input me-1"}} {{ form_2.err_header_3.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Таблицы
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_table_1|addclass:"form-check-input me-1"}} {{ form_2.err_table_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_table_2|addclass:"form-check-input me-1"}} {{ form_2.err_table_2.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_table_3|addclass:"form-check-input me-1"}} {{ form_2.err_table_3.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_table_4|addclass:"form-check-input me-1"}} {{ form_2.err_table_4.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Формулы
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_formula_1|addclass:"form-check-input me-1"}} {{ form_2.err_formula_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_formula_2|addclass:"form-check-input me-1"}} {{ form_2.err_formula_2.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_formula_3|addclass:"form-check-input me-1"}} {{ form_2.err_formula_3.label }}</li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-sm">
                <div class="card mb-2">
                  <div class="card-header">
                    Текст
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_text_1|addclass:"form-check-input me-1"}} {{ form_2.err_text_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_text_2|addclass:"form-check-input me-1"}} {{ form_2.err_text_2.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_text_3|addclass:"form-check-input me-1"}} {{ form_2.err_text_3.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_text_4|addclass:"form-check-input me-1"}} {{ form_2.err_text_4.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Списки
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_list_1|addclass:"form-check-input me-1"}} {{ form_2.err_list_1.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Рисунки
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_image_1|addclass:"form-check-input me-1"}} {{ form_2.err_image_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_image_2|addclass:"form-check-input me-1"}} {{ form_2.err_image_2.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_image_3|addclass:"form-check-input me-1"}} {{ form_2.err_image_3.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_image_4|addclass:"form-check-input me-1"}} {{ form_2.err_image_4.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Ссылки
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_link_1|addclass:"form-check-input me-1"}} {{ form_2.err_link_1.label }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_link_2|addclass:"form-check-input me-1"}} {{ form_2.err_link_2.label }}</li>
                    </ul>
                  </div>
                </div>
                <div class="card mb-2">
                  <div class="card-header">
                    Рамки
                  </div>
                  <div class="card-body">
                    <ul class="list-group border-0">
                      <li class="list-group-item border-0">{{ form_2.err_frame_1|addclass:"form-check-input me-1"}} {{ form_2.err_frame_1.label|safe }}</li>
                      <li class="list-group-item border-0">{{ form_2.err_frame_2|addclass:"form-check-input me-1"}} {{ form_2.err_frame_2.label }}</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <!-- end of error form body-->
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-success">
              Добавить замечания
            </button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
              Закрыть
            </button>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}