users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

verify/urls.py
from django.urls import path

from . import views


app_name = 'verify'

# Главные страницы
urlpatterns = [
     path('', views.index, name='index')
]

# Студенты
urlpatterns += [
     path('students/',
          views.student_list,
          name='student_list'),
     path('students/<str:username>/',
          views.student_active_check,
          name='student_active_check'),
]

# Группы
urlpatterns += [
     path('group/',
          views.group_list,
          name='group_list'),
     path('group/new_group/',
          views.new_group,
          name='new_group'),
     path('group/<slug:slug>/',
          views.group_students,
          name='group_students'),
]

# Проверки
urlpatterns += [
     path('user/<str:username>/check_list/',
          views.check_list,
          name='check_list'),
     path('user/<str:username>/archive/',
          views.archive,
          name='archive'),
     path('user/<str:username>/new_check/',
          views.new_check,
          name='new_check'),
     path('user/<str:username>/<int:check_id>/check_view/',
          views.check_view,
          name='check_view'),
     path('user/<str:username>/<int:check_id>/check_delete/',
          views.check_delete,
          name='check_delete'),
     path('user/<str:username>/<int:check_id>/check_archive/',
          views.check_archive,
          name='check_archive'),
     path('user/<str:username>/<int:check_id>/check_active/',
          views.check_active,
          name='check_active'),
]


# Замечания
urlpatterns += [
     path('user/<str:username>/<int:check_id>/add_remark/',
          views.add_remark,
          name='add_remark'),
     path('user/<str:username>/<int:check_id>/<int:remark_id>/delete_remark/',
          views.delete_remark,
          name='delete_remark'),
     path('user/<str:username>/<int:check_id>/<int:remark_id>/edit_remark/',
          views.edit_remark,
          name='edit_remark'),
]

verify/views/remark_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from verify.decorators import user_access
from verify.forms import RemarkEditForm, RemarkNavForm, RemarkStandartErrorForm
from verify.models import CheckOut, Remark


@login_required
@user_access
def add_remark(request, username, check_id):
    """Добавляет замечание на основе формы."""
    check_item = get_object_or_404(CheckOut, id=check_id)
    form_1 = RemarkNavForm(request.POST or None)
    form_2 = RemarkStandartErrorForm(request.POST or None)
    if form_1.is_valid() and form_2.is_valid():
        choice = form_1.cleaned_data['section']
        section = dict(form_1.fields['section'].choices)[choice]
        page_number = form_1.cleaned_data.get('page_number')
        paragraph = form_1.cleaned_data.get('paragraph')
        check_all = form_1.cleaned_data.get('check_all')
        custom_error = form_1.cleaned_data.get('custom_error')
        # Создаем кастомную ошибку, если это требуется
        if custom_error != '':
            check_all_status = None
            if check_all:
                check_all_status = form_1.fields.get('check_all').label,
            Remark.objects.get_or_create(
                section=section,
                page_number=page_number,
                paragraph=paragraph,
                check_all=check_all_status,
                text=custom_error,
                author=request.user,
                check_out=check_item
            )
        # Проверяем поля формы и создаем ошибки
        for field in form_2.fields:
            checkbox_result = form_2.cleaned_data.get(field)
            if checkbox_result:
                check_all_status = None
                if check_all:
                    check_all_status = form_1.fields.get('check_all').label,
                Remark.objects.get_or_create(
                    section=section,
                    page_number=page_number,
                    paragraph=paragraph,
                    check_all=check_all_status,
                    text=form_2.fields.get(field).label,
                    author=request.user,
                    check_out=check_item
                )
    return redirect('verify:check_view', username, check_id)


@login_required
@user_access
def edit_remark(request, username, check_id, remark_id):
    """Редактирует замечание."""
    remark = get_object_or_404(Remark, id=remark_id)
    form = RemarkEditForm(request.POST or None, instance=remark)
    if not form.is_valid():
        context = {'form': form}
        return render(request, 'verify/edit_remark.html', context)
    remark.save()
    return redirect('verify:check_view', username, check_id)


@login_required
@user_access
def delete_remark(request, username, check_id, remark_id):
    """Удаляет замечание."""
    remark = get_object_or_404(Remark, id=remark_id)
    remark.delete()
    return redirect('verify:check_view', username, check_id)

templates/includes/check_item.html
<div class="card mb-3 mt-1 shadow-sm">
  <div class="card-header"><strong>Отправлено на проверку:</strong> {{ check_item.check_date }}</div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Группа:</strong> <a class="link-danger" href="{% url 'verify:group_students' check_item.student.group.slug %}">{{ check_item.student.group }}</a>
    </li>
    <li class="list-group-item">
      <strong>ФИО:</strong> <a class="link-danger" href="#">{{ check_item.student.first_name }} {{ check_item.student.last_name }}</a>
    </li>
    {% if check_item.docx_file and check_item.pdf_file %}
    <li class="list-group-item">
      <strong>Диплом:</strong> <a class="link-danger" href="{{ check_item.docx_file.url }}">скачать docx</a>, <a class="link-danger" href="{{ check_item.pdf_file.url }}">скачать pdf</a>
    </li>
    {% endif %}
    <li class="list-group-item">
      <strong>Сопроводительная информация:</strong> {{ check_item.info }}
    </li>
    <li class="list-group-item">
      <strong>Статус: </strong>
      {% if not check_item.status %}
      Работа ожидает проверки
      {% else %}
      Работа проверена
      {% if check_item.remark.exists %}
      - требуется исправить замечания
      {% else %}
      - замечаний нет
      {% endif %}
      {% endif %}
    </li>

    <li class="list-group-item">
      {% if check_item.remark.exists %}
      <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{ check_item.id }}">
        Показать замечания ({{ check_item.remark.count}})
      </button>
      {% endif %}
      {% if not check_item.status %}
      {% if user.allow_manage  %}
      <a class="btn btn-outline-dark" href="{% url 'verify:check_view' user.username check_item.id %}" role="button">
        Проверить работу
      </a>
      <a class="btn btn-outline-secondary" href="{% url 'verify:check_archive' user.username check_item.id %}" role="button">
        В архив
      </a>
      {% else %}
      <a class="btn btn-outline-dark" href="{% url 'verify:check_delete' user.username check_item.id %}" role="button">
        Отменить проверку
      </a>
      {% endif %}
      {% else %}
      {% if user.allow_manage  %}
      <a class="btn btn-outline-dark" href="{% url 'verify:check_view' user.username check_item.id %}" role="button">
        Подробнее
      </a>
      <a class="btn btn-outline-success" href="{% url 'verify:check_active' user.username check_item.id %}" role="button">
        Вернуть в работу
      </a>
      <a class="btn btn-outline-secondary" href="{% url 'verify:check_delete' user.username check_item.id %}" role="button">
        Удалить
      </a>
      {% endif %}
      {% endif %}
    </li>
  </ul>
</div>

<div class="modal fade" id="exampleModal{{ check_item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Замечания по работе - {{ check_item.student.get_full_name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% include "includes/remarks.html" %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

templates/includes/footer.html
<footer>
  <div class="container-fluid bg-dark pt-4 pb-2">
    <div class="d-flex justify-content-center flex-row bd-highlight mb-3">
      <div>
        <p class="m-0 text-white text-center">Информационная система нормоконтроля © {% now "Y" %}, все права защищены. </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/group_item.html
<tr>
  <th scope="row">{{ forloop.counter }}</th>
  <td><a href="{% url 'verify:group_students' group.slug %}" class="link-light">{{ group }}</a></td>
  <td>{{ group.user.count }}</td>
</tr>

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark pt-3 pb-3">
  <div class="container-fluid">
    <div class="d-flex justify-content-start">
      <a href="{% url 'verify:index' %}" class="text-decoration-none">
        <span class="badge bg-danger p-2 fs-3">Normo</span>
        <span class="navbar-brand fs-3">control</span>
      </a>
    </div>
    <div class="d-flex justify-content-between">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'verify:index' %}">Главная</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'verify:check_list' user.username %}">Проверки</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'verify:archive' user.username %}">Архив</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="d-flex justify-content-end">
      {% if user.is_authenticated %}
      {% if user.allow_manage %}
      <a type="button" class="btn btn-danger m-2" style="width: 35px; height: 35px;" href="{% url 'verify:check_list' user.username %}">
        {{ check_count }}
        <span class="visually-hidden">Активные заявки на проверку</span>
      </a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% load thumbnail %}
              {% thumbnail user.image "200x200" crop="center"  as im %}
              <img class="card-img" src="{{ im.url }}" style="width: 35px;" />
              {% endthumbnail %}
              {{ request.user }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              {% if user.allow_manage %}
              <li><a class="dropdown-item" href="{% url 'verify:check_list' user.username %}">Работы на проверке</a></li>
              <li><a class="dropdown-item" href="{% url 'verify:archive' user.username %}">Архив</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'verify:group_list' %}">Группы</a></li>
              <li><a class="dropdown-item" href="{% url 'verify:student_list' %}">Студенты</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'verify:new_group' %}">Добавить группу</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'verify:new_check' user.username %}">Отправить на проверку</a></li>
              <li><a class="dropdown-item" href="{% url 'verify:check_list' user.username %}">Мои проверки</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>
            </ul>
          </li>
        </ul>
      </div>
      {% else %}
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Войти</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Регистрация</a></li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination d-flex justify-content-center">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link bg-white text-dark" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link bg-white text-dark">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link bg-dark text-white border-dark">{{ i }}
        <!--<span class="sr-only">(текущая)</span>-->
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link bg-white text-dark" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link bg-white text-dark" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link bg-white text-dark">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/recommends.html
<div class="card mb-3 mt-1 shadow-sm">
  {% if check_item.pdf_file_path %}
    <li class="list-group-item">
        <strong>Рекомендации:</strong> 
        <a href="/media/VKR.pdf" target="_blank">Открыть PDF</a>
    </li>
{% endif %}
</div>

templates/includes/remarks.html
<ul class="list-group list-group-flush">
  {% for item in check_item.remark.all %}
    <li class="list-group-item">
      <h6 class="mt-0">
        Замечание № {{ forloop.counter }}
      </h6>
      {{ item.section }}
      {% if item.page_number %}
        - страница {{ item.page_number }}
      {% endif %}

      {% if item.paragraph %}
        - абзац {{ item.paragraph }}
      {% endif %}
      <br>
      Описание: <span id="item-text">{{ item.text }}</span><br>
      {% if item.check_all %}
        <span class="text-danger"><b>Проверить по всей работе</b><br></span>
      {% endif %}

      {% if user.allow_manage %}
        <a class="btn btn-secondary btn-sm mt-1" href="{% url 'verify:delete_remark' username check_item.id item.id %}" role="button">
          Удалить
        </a>
        <a class="btn btn-danger btn-sm mt-1" href="{% url 'verify:edit_remark' username check_item.id item.id %}" role="button">
          Редактировать
        </a>
      {% else %}
        <a class="btn btn-danger btn-sm mt-1" href="#" onclick="openPDF('{{ item.text }}')" role="button">
          Справка по ошибке
        </a>
      {% endif %}

      <br>
      <small class="text-muted">{{ item.check_date }}</small>
    </li>
  {% endfor %}
</ul>


<script>
function openPDF(itemText) {
  const associativeContainer = {
    	"Неверно указана тема пояснительной записки.": "14", 
	"Неверно указан шифр пояснительной записки.": "14",
	"Факультет, кафедра или профиль указаны неверно.": "1",
	"Год написания пояснительной записки указан неверно.": "1",
	"Неверно указан номер или дата приказа.": "45", 
	"Неверно указаны исходные данные пояснительной записки.": "10", 
	"Неверно указано число листов в штампе структурного элемента.": "14", 
	"Закладка не определена.": "1", 
	"Некорректное форматирование текста.": "10", 
	"Орфографическая ошибка.": "16", 
	"Межстрочный интервал задан неверно.": "14", 
	"Абзацный отступ задан неверно.": "14", 
	"Заголовок расположен неверно.": "15", 
	"В заголовке используется неверный размер шрифта.": "15", 
	"Заголовок не соответствует содержанию.": "15", 
	"Список оформлен неверно.": "9",
	 "Таблица расположена неверно.": "22", 
	"Название таблицы расположено неверно.": "22", 
	"Номер таблицы указан неверно.": "22", 
	"Отсутствует ссылка на таблицу по тексту.": "22", 
	"Рисунок расположен неверно.": "20",
	 "Подрисуночная надпись расположена неверно.": "20", 
	"Некорректный номер рисунка.": "20", 
	"Отсутствует ссылка на рисунок по тексту.": "20", 
	"Формула расположена неверно.": "18", 
	"Номер формулы расположен неверно.": "3", 
	"Отсутствует ссылка на формулу по тексту.": "3", 
	"Не выдержан интервал от текста до рамки.": "3",
	"Неверно указано число листов в основной рамке.": "3", 
	"Отсутствуют ссылки на использованные источники.": "3", 
	"Ссылки на источники оформлены неверно.": "3"
  };

  if (itemText in associativeContainer) {
    const pdfPage = associativeContainer[itemText];
    const pdfUrl = '/media/VKR.pdf#page=' + pdfPage;
    window.open(pdfUrl, '_blank');
  } else {
    console.log("Ключ не найден");
  }
}
</script>

templates/includes/student_item.html
<tr>
  <th scope="row">{{ forloop.counter }}</th>
  <td>{{ student.get_full_name }}</td>
  <td>{{ student.email }}</td>
  <td>{{ student.username }}</td>
  <td>{{ student.group }}</td>
  <td>
    {% if student.checkout_student.last.status == False %}
    <a href="{% url 'verify:student_active_check' student.username %}" class="link-light">
      Проверить
    </a>
    {% else %}
    Отсутствует
    {% endif %}
  </td>
</tr>